### ISSUE TITLE
Some worker bug

### ISSUE THREAD

**Issue by thempel** [markovmodel/adaptivemd#31]
Any ideas what this is about? Just ran into it with the new master branch code. Excuse that the error messages are quadrupled due to the 4 Worker approach.
[job.914608.txt](https://github.com/markovmodel/adaptivemd/files/861681/job.914608.txt)

**Comment by thempel** [comment]
It always happens with a worker after one successful run, when starting the second run. I assume that #30 somehow removes the files that are being called.

**Comment by jhprinz** [comment]
Oh man, this one is real stupid...

The worker set the current directory to the `worker.{,,,}/` directory and while being inside it is deleted.
No problem there. But if you now call any function (in the next task) that uses any `os.getcwd()` like `os.path.abspath` it fails. 

The fix is easy...
